FROM node:16-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Make the jest executable (and all node_modules binaries) executable
RUN chmod +x node_modules/.bin/*

# OR run jest with npx
CMD ["npx", "jest"]