version: '3.8'

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - NODE_ENV=test
      - DB_HOST=test-db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=nurda0101
      - DB_NAME=ecotrend_test
    depends_on:
      - test-db
    networks:
      - test-network

  test-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=nurda0101
      - MYSQL_DATABASE=ecotrend_test
      - MYSQL_ROOT_HOST=%
    ports:
      - "33306:3306"
    command: >
      --default-authentication-plugin=mysql_native_password 
      --character-set-server=utf8mb4 
      --collation-server=utf8mb4_unicode_ci 
      --bind-address=0.0.0.0
      --skip-name-resolve
    volumes:
      - ./init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql
    networks:
      - test-network

networks:
  test-network:
    driver: bridge