FROM node:16-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Make all executables in node_modules/.bin directory executable
RUN chmod +x node_modules/.bin/*

# Add explicit timeout to Jest
CMD ["sh", "-c", "sleep 15 && npx jest --forceExit --detectOpenHandles --verbose --testTimeout=60000"]